version: "3.1"
services:

    redis:
      image: redis:latest
      container_name: golang-microservices-redis
      ports:
       - "6379:6379"
      networks:
            golang_microservices_net:
                ipv4_address: 172.28.1.1

    postgres:
      image: postgres:latest
      container_name: golang-microservices-postgres
      volumes:
         - "./data/product/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
      ports:
       - "5432:5432"
      networks:
            golang_microservices_net:
                ipv4_address: 172.28.1.2
    
networks:
    golang_microservices_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16